# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='description',
        ),
    ]
